jobs:
  tests:
    strategy:
      matrix:
        include:
          - ruby: "2.7.0"
            dry_schema_from_main: "true"
            dry_types_from_main: "true"
            dry_configurable_from_main: "true"
    env:
      DRY_SCHEMA_FROM_MAIN: ${{matrix.dry_schema_from_main}}
      DRY_TYPES_FROM_MAIN: ${{matrix.dry_types_from_main}}
      DRY_CONFIGURABLE_FROM_MAIN: ${{matrix.dry_configurable_from_main}}
